---
title: Creating and Working with Individual Client Folders
filename: create_clients.mdx
date: 09/02/2024
keywords: "Data Organization, Client Case Management"
author: "Shawn Gilroy"
index: 3
---

The **Individual** folders, which are nested under respective **Group** folders, are a critical part of the data management strategy and hierarchy. These folders are dedicated to housing _all_ data related to a specific participant or subject within the larger context of a research study or clinical service (e.g., inpatient vs. outpatient care). Each **Individual** folder is named after the participant it represents, typically using a unique identifier such as a participant ID or name, like "Participant_001" or "Subject_A." This structure ensures that all data collected from a particular individual is systematically stored in one location, facilitating easy access and analysis. As a note, you must follow research and clinical data management practices for your institution when naming and storing data; however, Data Tracker works only on local data and no information is ever transmitted to the internet.

The primary purpose of the **Individual** folder is to maintain the integrity and continuity of data for each participant throughout the process of recording and interpreting data (e.g., research, care). Since coordinating support often involves multiple Evaluations (e.g., assessments over time), the **Individual** folder acts as a centralized repository where all data related to a single participant are aggregated. This organization is particularly beneficial in longitudinal and times-series studies, where tracking changes in behavior or responses over time is central to the approach. By keeping all relevant data within one **Individual** folder, researchers can easily follow the progression of a participant's performance or responses, ensuring that no data is lost or misattributed.

For example, consider a study examining the effects of communication training on social interactions in children with autism. Each child participating in the study would have their own **Individual** folder, such as "Participant_001" or "Child_Autism_001." Within this folder, researchers would store all data collected from that child, including baseline assessments, intervention sessions, and follow-up evaluations. This approach allows researchers to track the child's progress over time, compare results across different assessments, and analyze the impact of the intervention on their social skills. By maintaining a clear and consistent structure for **Individual** folders, researchers can ensure that data is well-organized, accessible, and accurately attributed to the correct participant.

The rationale for this structure is to provide a systematic way to organize participant-specific data, ensuring that all information is easily traceable back to the individual it pertains. This not only aids in data analysis but also supports accurate record-keeping, which is vital for the credibility and reproducibility of research findings. Furthermore, this organization helps prevent data from different participants from becoming mixed up, reducing the likelihood of errors in data interpretation or reporting. By implementing a clear and consistent naming convention for **Individual** folders, the program enhances data management practices, making it easier for researchers to handle large datasets and collaborate effectively within research teams.
