/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as DocumentationIndexRouteImport } from './routes/documentation/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DocumentationSlugRouteImport } from './routes/documentation/$slug'
import { Route as DashboardSyncRouteImport } from './routes/dashboard/sync'
import { Route as SessionGroupIndexRouteImport } from './routes/session/$group/index'
import { Route as SessionGroupIndividualIndexRouteImport } from './routes/session/$group/$individual/index'
import { Route as SessionGroupIndividualKeysetsIndexRouteImport } from './routes/session/$group/$individual/keysets/index'
import { Route as SessionGroupIndividualImportIndexRouteImport } from './routes/session/$group/$individual/import/index'
import { Route as SessionGroupIndividualEvaluationIndexRouteImport } from './routes/session/$group/$individual/$evaluation/index'
import { Route as SessionGroupIndividualKeysetsImportRouteImport } from './routes/session/$group/$individual/keysets/import'
import { Route as SessionGroupIndividualKeysetsKeysetRouteImport } from './routes/session/$group/$individual/keysets/$keyset'
import { Route as SessionGroupIndividualEvaluationViewRouteImport } from './routes/session/$group/$individual/$evaluation/view'
import { Route as SessionGroupIndividualEvaluationReliRouteImport } from './routes/session/$group/$individual/$evaluation/reli'
import { Route as SessionGroupIndividualEvaluationRateRouteImport } from './routes/session/$group/$individual/$evaluation/rate'
import { Route as SessionGroupIndividualEvaluationProportionRouteImport } from './routes/session/$group/$individual/$evaluation/proportion'
import { Route as SessionGroupIndividualEvaluationHistoryIndexRouteImport } from './routes/session/$group/$individual/$evaluation/history.index'
import { Route as SessionGroupIndividualEvaluationRunKeysetRouteImport } from './routes/session/$group/$individual/$evaluation/run.$keyset'
import { Route as SessionGroupIndividualEvaluationHistoryViewFileRouteImport } from './routes/session/$group/$individual/$evaluation/history.view.$file'
import { Route as SessionGroupIndividualEvaluationHistoryEditFileRouteImport } from './routes/session/$group/$individual/$evaluation/history.edit.$file'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationIndexRoute = DocumentationIndexRouteImport.update({
  id: '/documentation/',
  path: '/documentation/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationSlugRoute = DocumentationSlugRouteImport.update({
  id: '/documentation/$slug',
  path: '/documentation/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSyncRoute = DashboardSyncRouteImport.update({
  id: '/dashboard/sync',
  path: '/dashboard/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionGroupIndexRoute = SessionGroupIndexRouteImport.update({
  id: '/session/$group/',
  path: '/session/$group/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionGroupIndividualIndexRoute =
  SessionGroupIndividualIndexRouteImport.update({
    id: '/session/$group/$individual/',
    path: '/session/$group/$individual/',
    getParentRoute: () => rootRouteImport,
  } as any)
const SessionGroupIndividualKeysetsIndexRoute =
  SessionGroupIndividualKeysetsIndexRouteImport.update({
    id: '/session/$group/$individual/keysets/',
    path: '/session/$group/$individual/keysets/',
    getParentRoute: () => rootRouteImport,
  } as any)
const SessionGroupIndividualImportIndexRoute =
  SessionGroupIndividualImportIndexRouteImport.update({
    id: '/session/$group/$individual/import/',
    path: '/session/$group/$individual/import/',
    getParentRoute: () => rootRouteImport,
  } as any)
const SessionGroupIndividualEvaluationIndexRoute =
  SessionGroupIndividualEvaluationIndexRouteImport.update({
    id: '/session/$group/$individual/$evaluation/',
    path: '/session/$group/$individual/$evaluation/',
    getParentRoute: () => rootRouteImport,
  } as any)
const SessionGroupIndividualKeysetsImportRoute =
  SessionGroupIndividualKeysetsImportRouteImport.update({
    id: '/session/$group/$individual/keysets/import',
    path: '/session/$group/$individual/keysets/import',
    getParentRoute: () => rootRouteImport,
  } as any)
const SessionGroupIndividualKeysetsKeysetRoute =
  SessionGroupIndividualKeysetsKeysetRouteImport.update({
    id: '/session/$group/$individual/keysets/$keyset',
    path: '/session/$group/$individual/keysets/$keyset',
    getParentRoute: () => rootRouteImport,
  } as any)
const SessionGroupIndividualEvaluationViewRoute =
  SessionGroupIndividualEvaluationViewRouteImport.update({
    id: '/session/$group/$individual/$evaluation/view',
    path: '/session/$group/$individual/$evaluation/view',
    getParentRoute: () => rootRouteImport,
  } as any)
const SessionGroupIndividualEvaluationReliRoute =
  SessionGroupIndividualEvaluationReliRouteImport.update({
    id: '/session/$group/$individual/$evaluation/reli',
    path: '/session/$group/$individual/$evaluation/reli',
    getParentRoute: () => rootRouteImport,
  } as any)
const SessionGroupIndividualEvaluationRateRoute =
  SessionGroupIndividualEvaluationRateRouteImport.update({
    id: '/session/$group/$individual/$evaluation/rate',
    path: '/session/$group/$individual/$evaluation/rate',
    getParentRoute: () => rootRouteImport,
  } as any)
const SessionGroupIndividualEvaluationProportionRoute =
  SessionGroupIndividualEvaluationProportionRouteImport.update({
    id: '/session/$group/$individual/$evaluation/proportion',
    path: '/session/$group/$individual/$evaluation/proportion',
    getParentRoute: () => rootRouteImport,
  } as any)
const SessionGroupIndividualEvaluationHistoryIndexRoute =
  SessionGroupIndividualEvaluationHistoryIndexRouteImport.update({
    id: '/session/$group/$individual/$evaluation/history/',
    path: '/session/$group/$individual/$evaluation/history/',
    getParentRoute: () => rootRouteImport,
  } as any)
const SessionGroupIndividualEvaluationRunKeysetRoute =
  SessionGroupIndividualEvaluationRunKeysetRouteImport.update({
    id: '/session/$group/$individual/$evaluation/run/$keyset',
    path: '/session/$group/$individual/$evaluation/run/$keyset',
    getParentRoute: () => rootRouteImport,
  } as any)
const SessionGroupIndividualEvaluationHistoryViewFileRoute =
  SessionGroupIndividualEvaluationHistoryViewFileRouteImport.update({
    id: '/session/$group/$individual/$evaluation/history/view/$file',
    path: '/session/$group/$individual/$evaluation/history/view/$file',
    getParentRoute: () => rootRouteImport,
  } as any)
const SessionGroupIndividualEvaluationHistoryEditFileRoute =
  SessionGroupIndividualEvaluationHistoryEditFileRouteImport.update({
    id: '/session/$group/$individual/$evaluation/history/edit/$file',
    path: '/session/$group/$individual/$evaluation/history/edit/$file',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard/sync': typeof DashboardSyncRoute
  '/documentation/$slug': typeof DocumentationSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/documentation/': typeof DocumentationIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/session/$group/': typeof SessionGroupIndexRoute
  '/session/$group/$individual/': typeof SessionGroupIndividualIndexRoute
  '/session/$group/$individual/$evaluation/proportion': typeof SessionGroupIndividualEvaluationProportionRoute
  '/session/$group/$individual/$evaluation/rate': typeof SessionGroupIndividualEvaluationRateRoute
  '/session/$group/$individual/$evaluation/reli': typeof SessionGroupIndividualEvaluationReliRoute
  '/session/$group/$individual/$evaluation/view': typeof SessionGroupIndividualEvaluationViewRoute
  '/session/$group/$individual/keysets/$keyset': typeof SessionGroupIndividualKeysetsKeysetRoute
  '/session/$group/$individual/keysets/import': typeof SessionGroupIndividualKeysetsImportRoute
  '/session/$group/$individual/$evaluation/': typeof SessionGroupIndividualEvaluationIndexRoute
  '/session/$group/$individual/import/': typeof SessionGroupIndividualImportIndexRoute
  '/session/$group/$individual/keysets/': typeof SessionGroupIndividualKeysetsIndexRoute
  '/session/$group/$individual/$evaluation/run/$keyset': typeof SessionGroupIndividualEvaluationRunKeysetRoute
  '/session/$group/$individual/$evaluation/history/': typeof SessionGroupIndividualEvaluationHistoryIndexRoute
  '/session/$group/$individual/$evaluation/history/edit/$file': typeof SessionGroupIndividualEvaluationHistoryEditFileRoute
  '/session/$group/$individual/$evaluation/history/view/$file': typeof SessionGroupIndividualEvaluationHistoryViewFileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/sync': typeof DashboardSyncRoute
  '/documentation/$slug': typeof DocumentationSlugRoute
  '/dashboard': typeof DashboardIndexRoute
  '/documentation': typeof DocumentationIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/session/$group': typeof SessionGroupIndexRoute
  '/session/$group/$individual': typeof SessionGroupIndividualIndexRoute
  '/session/$group/$individual/$evaluation/proportion': typeof SessionGroupIndividualEvaluationProportionRoute
  '/session/$group/$individual/$evaluation/rate': typeof SessionGroupIndividualEvaluationRateRoute
  '/session/$group/$individual/$evaluation/reli': typeof SessionGroupIndividualEvaluationReliRoute
  '/session/$group/$individual/$evaluation/view': typeof SessionGroupIndividualEvaluationViewRoute
  '/session/$group/$individual/keysets/$keyset': typeof SessionGroupIndividualKeysetsKeysetRoute
  '/session/$group/$individual/keysets/import': typeof SessionGroupIndividualKeysetsImportRoute
  '/session/$group/$individual/$evaluation': typeof SessionGroupIndividualEvaluationIndexRoute
  '/session/$group/$individual/import': typeof SessionGroupIndividualImportIndexRoute
  '/session/$group/$individual/keysets': typeof SessionGroupIndividualKeysetsIndexRoute
  '/session/$group/$individual/$evaluation/run/$keyset': typeof SessionGroupIndividualEvaluationRunKeysetRoute
  '/session/$group/$individual/$evaluation/history': typeof SessionGroupIndividualEvaluationHistoryIndexRoute
  '/session/$group/$individual/$evaluation/history/edit/$file': typeof SessionGroupIndividualEvaluationHistoryEditFileRoute
  '/session/$group/$individual/$evaluation/history/view/$file': typeof SessionGroupIndividualEvaluationHistoryViewFileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard/sync': typeof DashboardSyncRoute
  '/documentation/$slug': typeof DocumentationSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/documentation/': typeof DocumentationIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/session/$group/': typeof SessionGroupIndexRoute
  '/session/$group/$individual/': typeof SessionGroupIndividualIndexRoute
  '/session/$group/$individual/$evaluation/proportion': typeof SessionGroupIndividualEvaluationProportionRoute
  '/session/$group/$individual/$evaluation/rate': typeof SessionGroupIndividualEvaluationRateRoute
  '/session/$group/$individual/$evaluation/reli': typeof SessionGroupIndividualEvaluationReliRoute
  '/session/$group/$individual/$evaluation/view': typeof SessionGroupIndividualEvaluationViewRoute
  '/session/$group/$individual/keysets/$keyset': typeof SessionGroupIndividualKeysetsKeysetRoute
  '/session/$group/$individual/keysets/import': typeof SessionGroupIndividualKeysetsImportRoute
  '/session/$group/$individual/$evaluation/': typeof SessionGroupIndividualEvaluationIndexRoute
  '/session/$group/$individual/import/': typeof SessionGroupIndividualImportIndexRoute
  '/session/$group/$individual/keysets/': typeof SessionGroupIndividualKeysetsIndexRoute
  '/session/$group/$individual/$evaluation/run/$keyset': typeof SessionGroupIndividualEvaluationRunKeysetRoute
  '/session/$group/$individual/$evaluation/history/': typeof SessionGroupIndividualEvaluationHistoryIndexRoute
  '/session/$group/$individual/$evaluation/history/edit/$file': typeof SessionGroupIndividualEvaluationHistoryEditFileRoute
  '/session/$group/$individual/$evaluation/history/view/$file': typeof SessionGroupIndividualEvaluationHistoryViewFileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard/sync'
    | '/documentation/$slug'
    | '/dashboard/'
    | '/documentation/'
    | '/settings/'
    | '/session/$group/'
    | '/session/$group/$individual/'
    | '/session/$group/$individual/$evaluation/proportion'
    | '/session/$group/$individual/$evaluation/rate'
    | '/session/$group/$individual/$evaluation/reli'
    | '/session/$group/$individual/$evaluation/view'
    | '/session/$group/$individual/keysets/$keyset'
    | '/session/$group/$individual/keysets/import'
    | '/session/$group/$individual/$evaluation/'
    | '/session/$group/$individual/import/'
    | '/session/$group/$individual/keysets/'
    | '/session/$group/$individual/$evaluation/run/$keyset'
    | '/session/$group/$individual/$evaluation/history/'
    | '/session/$group/$individual/$evaluation/history/edit/$file'
    | '/session/$group/$individual/$evaluation/history/view/$file'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/sync'
    | '/documentation/$slug'
    | '/dashboard'
    | '/documentation'
    | '/settings'
    | '/session/$group'
    | '/session/$group/$individual'
    | '/session/$group/$individual/$evaluation/proportion'
    | '/session/$group/$individual/$evaluation/rate'
    | '/session/$group/$individual/$evaluation/reli'
    | '/session/$group/$individual/$evaluation/view'
    | '/session/$group/$individual/keysets/$keyset'
    | '/session/$group/$individual/keysets/import'
    | '/session/$group/$individual/$evaluation'
    | '/session/$group/$individual/import'
    | '/session/$group/$individual/keysets'
    | '/session/$group/$individual/$evaluation/run/$keyset'
    | '/session/$group/$individual/$evaluation/history'
    | '/session/$group/$individual/$evaluation/history/edit/$file'
    | '/session/$group/$individual/$evaluation/history/view/$file'
  id:
    | '__root__'
    | '/'
    | '/dashboard/sync'
    | '/documentation/$slug'
    | '/dashboard/'
    | '/documentation/'
    | '/settings/'
    | '/session/$group/'
    | '/session/$group/$individual/'
    | '/session/$group/$individual/$evaluation/proportion'
    | '/session/$group/$individual/$evaluation/rate'
    | '/session/$group/$individual/$evaluation/reli'
    | '/session/$group/$individual/$evaluation/view'
    | '/session/$group/$individual/keysets/$keyset'
    | '/session/$group/$individual/keysets/import'
    | '/session/$group/$individual/$evaluation/'
    | '/session/$group/$individual/import/'
    | '/session/$group/$individual/keysets/'
    | '/session/$group/$individual/$evaluation/run/$keyset'
    | '/session/$group/$individual/$evaluation/history/'
    | '/session/$group/$individual/$evaluation/history/edit/$file'
    | '/session/$group/$individual/$evaluation/history/view/$file'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardSyncRoute: typeof DashboardSyncRoute
  DocumentationSlugRoute: typeof DocumentationSlugRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DocumentationIndexRoute: typeof DocumentationIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SessionGroupIndexRoute: typeof SessionGroupIndexRoute
  SessionGroupIndividualIndexRoute: typeof SessionGroupIndividualIndexRoute
  SessionGroupIndividualEvaluationProportionRoute: typeof SessionGroupIndividualEvaluationProportionRoute
  SessionGroupIndividualEvaluationRateRoute: typeof SessionGroupIndividualEvaluationRateRoute
  SessionGroupIndividualEvaluationReliRoute: typeof SessionGroupIndividualEvaluationReliRoute
  SessionGroupIndividualEvaluationViewRoute: typeof SessionGroupIndividualEvaluationViewRoute
  SessionGroupIndividualKeysetsKeysetRoute: typeof SessionGroupIndividualKeysetsKeysetRoute
  SessionGroupIndividualKeysetsImportRoute: typeof SessionGroupIndividualKeysetsImportRoute
  SessionGroupIndividualEvaluationIndexRoute: typeof SessionGroupIndividualEvaluationIndexRoute
  SessionGroupIndividualImportIndexRoute: typeof SessionGroupIndividualImportIndexRoute
  SessionGroupIndividualKeysetsIndexRoute: typeof SessionGroupIndividualKeysetsIndexRoute
  SessionGroupIndividualEvaluationRunKeysetRoute: typeof SessionGroupIndividualEvaluationRunKeysetRoute
  SessionGroupIndividualEvaluationHistoryIndexRoute: typeof SessionGroupIndividualEvaluationHistoryIndexRoute
  SessionGroupIndividualEvaluationHistoryEditFileRoute: typeof SessionGroupIndividualEvaluationHistoryEditFileRoute
  SessionGroupIndividualEvaluationHistoryViewFileRoute: typeof SessionGroupIndividualEvaluationHistoryViewFileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation/': {
      id: '/documentation/'
      path: '/documentation'
      fullPath: '/documentation/'
      preLoaderRoute: typeof DocumentationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation/$slug': {
      id: '/documentation/$slug'
      path: '/documentation/$slug'
      fullPath: '/documentation/$slug'
      preLoaderRoute: typeof DocumentationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/sync': {
      id: '/dashboard/sync'
      path: '/dashboard/sync'
      fullPath: '/dashboard/sync'
      preLoaderRoute: typeof DashboardSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$group/': {
      id: '/session/$group/'
      path: '/session/$group'
      fullPath: '/session/$group/'
      preLoaderRoute: typeof SessionGroupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$group/$individual/': {
      id: '/session/$group/$individual/'
      path: '/session/$group/$individual'
      fullPath: '/session/$group/$individual/'
      preLoaderRoute: typeof SessionGroupIndividualIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$group/$individual/keysets/': {
      id: '/session/$group/$individual/keysets/'
      path: '/session/$group/$individual/keysets'
      fullPath: '/session/$group/$individual/keysets/'
      preLoaderRoute: typeof SessionGroupIndividualKeysetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$group/$individual/import/': {
      id: '/session/$group/$individual/import/'
      path: '/session/$group/$individual/import'
      fullPath: '/session/$group/$individual/import/'
      preLoaderRoute: typeof SessionGroupIndividualImportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$group/$individual/$evaluation/': {
      id: '/session/$group/$individual/$evaluation/'
      path: '/session/$group/$individual/$evaluation'
      fullPath: '/session/$group/$individual/$evaluation/'
      preLoaderRoute: typeof SessionGroupIndividualEvaluationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$group/$individual/keysets/import': {
      id: '/session/$group/$individual/keysets/import'
      path: '/session/$group/$individual/keysets/import'
      fullPath: '/session/$group/$individual/keysets/import'
      preLoaderRoute: typeof SessionGroupIndividualKeysetsImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$group/$individual/keysets/$keyset': {
      id: '/session/$group/$individual/keysets/$keyset'
      path: '/session/$group/$individual/keysets/$keyset'
      fullPath: '/session/$group/$individual/keysets/$keyset'
      preLoaderRoute: typeof SessionGroupIndividualKeysetsKeysetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$group/$individual/$evaluation/view': {
      id: '/session/$group/$individual/$evaluation/view'
      path: '/session/$group/$individual/$evaluation/view'
      fullPath: '/session/$group/$individual/$evaluation/view'
      preLoaderRoute: typeof SessionGroupIndividualEvaluationViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$group/$individual/$evaluation/reli': {
      id: '/session/$group/$individual/$evaluation/reli'
      path: '/session/$group/$individual/$evaluation/reli'
      fullPath: '/session/$group/$individual/$evaluation/reli'
      preLoaderRoute: typeof SessionGroupIndividualEvaluationReliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$group/$individual/$evaluation/rate': {
      id: '/session/$group/$individual/$evaluation/rate'
      path: '/session/$group/$individual/$evaluation/rate'
      fullPath: '/session/$group/$individual/$evaluation/rate'
      preLoaderRoute: typeof SessionGroupIndividualEvaluationRateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$group/$individual/$evaluation/proportion': {
      id: '/session/$group/$individual/$evaluation/proportion'
      path: '/session/$group/$individual/$evaluation/proportion'
      fullPath: '/session/$group/$individual/$evaluation/proportion'
      preLoaderRoute: typeof SessionGroupIndividualEvaluationProportionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$group/$individual/$evaluation/history/': {
      id: '/session/$group/$individual/$evaluation/history/'
      path: '/session/$group/$individual/$evaluation/history'
      fullPath: '/session/$group/$individual/$evaluation/history/'
      preLoaderRoute: typeof SessionGroupIndividualEvaluationHistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$group/$individual/$evaluation/run/$keyset': {
      id: '/session/$group/$individual/$evaluation/run/$keyset'
      path: '/session/$group/$individual/$evaluation/run/$keyset'
      fullPath: '/session/$group/$individual/$evaluation/run/$keyset'
      preLoaderRoute: typeof SessionGroupIndividualEvaluationRunKeysetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$group/$individual/$evaluation/history/view/$file': {
      id: '/session/$group/$individual/$evaluation/history/view/$file'
      path: '/session/$group/$individual/$evaluation/history/view/$file'
      fullPath: '/session/$group/$individual/$evaluation/history/view/$file'
      preLoaderRoute: typeof SessionGroupIndividualEvaluationHistoryViewFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$group/$individual/$evaluation/history/edit/$file': {
      id: '/session/$group/$individual/$evaluation/history/edit/$file'
      path: '/session/$group/$individual/$evaluation/history/edit/$file'
      fullPath: '/session/$group/$individual/$evaluation/history/edit/$file'
      preLoaderRoute: typeof SessionGroupIndividualEvaluationHistoryEditFileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardSyncRoute: DashboardSyncRoute,
  DocumentationSlugRoute: DocumentationSlugRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DocumentationIndexRoute: DocumentationIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SessionGroupIndexRoute: SessionGroupIndexRoute,
  SessionGroupIndividualIndexRoute: SessionGroupIndividualIndexRoute,
  SessionGroupIndividualEvaluationProportionRoute:
    SessionGroupIndividualEvaluationProportionRoute,
  SessionGroupIndividualEvaluationRateRoute:
    SessionGroupIndividualEvaluationRateRoute,
  SessionGroupIndividualEvaluationReliRoute:
    SessionGroupIndividualEvaluationReliRoute,
  SessionGroupIndividualEvaluationViewRoute:
    SessionGroupIndividualEvaluationViewRoute,
  SessionGroupIndividualKeysetsKeysetRoute:
    SessionGroupIndividualKeysetsKeysetRoute,
  SessionGroupIndividualKeysetsImportRoute:
    SessionGroupIndividualKeysetsImportRoute,
  SessionGroupIndividualEvaluationIndexRoute:
    SessionGroupIndividualEvaluationIndexRoute,
  SessionGroupIndividualImportIndexRoute:
    SessionGroupIndividualImportIndexRoute,
  SessionGroupIndividualKeysetsIndexRoute:
    SessionGroupIndividualKeysetsIndexRoute,
  SessionGroupIndividualEvaluationRunKeysetRoute:
    SessionGroupIndividualEvaluationRunKeysetRoute,
  SessionGroupIndividualEvaluationHistoryIndexRoute:
    SessionGroupIndividualEvaluationHistoryIndexRoute,
  SessionGroupIndividualEvaluationHistoryEditFileRoute:
    SessionGroupIndividualEvaluationHistoryEditFileRoute,
  SessionGroupIndividualEvaluationHistoryViewFileRoute:
    SessionGroupIndividualEvaluationHistoryViewFileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
