/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as DocumentationIndexRouteImport } from './routes/documentation/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DocumentationSlugRouteImport } from './routes/documentation/$slug'
import { Route as DashboardSyncIndexRouteImport } from './routes/dashboard/sync/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationIndexRoute = DocumentationIndexRouteImport.update({
  id: '/documentation/',
  path: '/documentation/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationSlugRoute = DocumentationSlugRouteImport.update({
  id: '/documentation/$slug',
  path: '/documentation/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSyncIndexRoute = DashboardSyncIndexRouteImport.update({
  id: '/dashboard/sync/',
  path: '/dashboard/sync/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/documentation/$slug': typeof DocumentationSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/documentation/': typeof DocumentationIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/dashboard/sync/': typeof DashboardSyncIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/documentation/$slug': typeof DocumentationSlugRoute
  '/dashboard': typeof DashboardIndexRoute
  '/documentation': typeof DocumentationIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/dashboard/sync': typeof DashboardSyncIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/documentation/$slug': typeof DocumentationSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/documentation/': typeof DocumentationIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/dashboard/sync/': typeof DashboardSyncIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/documentation/$slug'
    | '/dashboard/'
    | '/documentation/'
    | '/settings/'
    | '/dashboard/sync/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/documentation/$slug'
    | '/dashboard'
    | '/documentation'
    | '/settings'
    | '/dashboard/sync'
  id:
    | '__root__'
    | '/'
    | '/documentation/$slug'
    | '/dashboard/'
    | '/documentation/'
    | '/settings/'
    | '/dashboard/sync/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocumentationSlugRoute: typeof DocumentationSlugRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DocumentationIndexRoute: typeof DocumentationIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  DashboardSyncIndexRoute: typeof DashboardSyncIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation/': {
      id: '/documentation/'
      path: '/documentation'
      fullPath: '/documentation/'
      preLoaderRoute: typeof DocumentationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation/$slug': {
      id: '/documentation/$slug'
      path: '/documentation/$slug'
      fullPath: '/documentation/$slug'
      preLoaderRoute: typeof DocumentationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/sync/': {
      id: '/dashboard/sync/'
      path: '/dashboard/sync'
      fullPath: '/dashboard/sync/'
      preLoaderRoute: typeof DashboardSyncIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocumentationSlugRoute: DocumentationSlugRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DocumentationIndexRoute: DocumentationIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  DashboardSyncIndexRoute: DashboardSyncIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
