name: Release Builder
on:
  push:
    branches:
      - testing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run build
        run: npm run build --mode island

      - name: Zip files
        run: zip -r island-build.zip dist-island

      - name: Get Version
        id: get_version
        run: |
          const fs = require('fs');
          const version = JSON.parse(fs.readFileSync('./package.json')).version;
          console.log(`::set-output name=VERSION::${version}`);
        shell: node

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: island-build-${{ steps.get_version.outputs.VERSION }}
          release_name: Island Build ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
