name: Release Builder
on:
  push:
    branches:
      - testing

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run build
        run: npm run build-island

      - name: Get Version
        shell: bash
        id: get-version
        run: echo "version=$(node ./.github/workflows/get-version.js)" >> $GITHUB_OUTPUT

      - name: Zip files
        run: |
          cd dist-island && zip -r ../DataTracker-Island-build.zip .

      - name: Create Release
        id: create-release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.get-version.outputs.version }}
          allowUpdates: true
          name: DataTracker Island Build ${{ steps.get-version.outputs.version }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: DataTracker-Island-build.zip
