name: Release Builder
on:
  push:
    branches:
      - testing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run build
        run: npm run build-island

      - name: Zip files
        run: zip -r island-build.zip dist-island

      - name: Get Version
        shell: bash
        id: get-version
        run: echo "::set-output name=version::$(node ./.github/workflows/get-version.js)"

      - name: Create Release (V2)
        uses: ncipollo/release-action@v2
        with:
          allowUpdates: true
          name: Island Build Version ${{ steps.get-version.outputs.version }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: island-build.zip
          tag: island-build-${{ steps.get-version.outputs.version }}
          files: island-build.zip
